# Generated by Django 6.0 on 2026-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_signuptable_logintable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='username',
        ),
        migrations.AddField(
            model_name='logintable',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
