# Generated by Django 6.0.1 on 2026-02-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_logintable_username_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logintable",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Login Credential",
                "verbose_name_plural": "Login Credentials",
            },
        ),
        migrations.AlterModelOptions(
            name="signuptable",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Signup Entry",
                "verbose_name_plural": "Signup Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["user__username"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="logintable",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="logintable",
            name="institution_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="logintable",
            name="signup",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_credentials",
                to="accounts.signuptable",
            ),
        ),
        migrations.AlterField(
            model_name="signuptable",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="signuptable",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="signuptable",
            name="institution_name",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("institution_admin", "Institution Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                db_index=True,
                default="institution_admin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["institution", "role"], name="accounts_us_institu_c1a975_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="logintable",
            table="accounts_logintable",
        ),
        migrations.AlterModelTable(
            name="signuptable",
            table="accounts_signuptable",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="accounts_userprofile",
        ),
    ]
