# Generated by Django 6.0.1 on 2026-02-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_logintable_options_alter_signuptable_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logintable",
            options={},
        ),
        migrations.AlterModelOptions(
            name="signuptable",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="accounts_us_institu_c1a975_idx",
        ),
        migrations.AlterField(
            model_name="logintable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="logintable",
            name="institution_name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="logintable",
            name="signup",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.signuptable"
            ),
        ),
        migrations.AlterField(
            model_name="signuptable",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="signuptable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="signuptable",
            name="institution_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("institution_admin", "Institution Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                default="institution_admin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="logintable",
            table=None,
        ),
        migrations.AlterModelTable(
            name="signuptable",
            table=None,
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table=None,
        ),
    ]
