# Generated by Django 6.0.1 on 2026-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("Full-Time", "Full-Time"),
                    ("Part-Time", "Part-Time"),
                    ("Contract", "Contract"),
                    ("Guest", "Guest"),
                ],
                default="Full-Time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
