# Generated by Django 6.0.1 on 2026-02-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0004_alter_institution_options_alter_news_options_and_more"),
        ("teacher", "0003_teacher_address_teacher_contract_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["employee_id"],
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="employee_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["institution", "department"],
                name="teacher_tea_institu_4649e7_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="teacher",
            table="teacher_teacher",
        ),
    ]
