# Generated by Django 6.0.1 on 2026-02-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_options_alter_news_options_and_more"),
        ("teacher", "0004_alter_teacher_options_alter_teacher_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="teacher",
            name="teacher_tea_institu_4649e7_idx",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="employee_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="teacher",
            table=None,
        ),
    ]
