# Generated by Django 6.0.1 on 2026-02-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0005_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="department",
        ),
    ]
