# Generated by Django 6.0.1 on 2026-02-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_options_alter_news_options_and_more"),
        ("teacher", "0006_remove_teacher_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.department",
            ),
        ),
    ]
