# Generated by Django 6.0.1 on 2026-02-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_branch"),
        ("teacher", "0007_teacher_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.branch",
            ),
        ),
    ]
