# Generated by Django 6.0.1 on 2026-02-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_eventtypecolor_academiccalendar_calendarevent"),
        ("institution", "0008_academiccalendarevent"),
        ("marksheet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="department",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="institution.department"
            ),
        ),
        migrations.AlterField(
            model_name="marks",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.course"
            ),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.course"
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
