# Generated by Django 6.0.1 on 2026-02-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0002_remove_subject_department_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
