# Generated by Django 6.0 on 2026-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
