# Generated by Django 6.0.1 on 2026-02-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("institution", "name")},
        ),
    ]
