# Generated by Django 6.0.1 on 2026-02-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0006_alter_department_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_feed",
                to="institution.institution",
            ),
        ),
    ]
