# Generated by Django 6.0.1 on 2026-02-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0007_news_institution"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("exam", "Examination"),
                            ("holiday", "Holiday"),
                            ("semester_start", "Semester Start"),
                            ("semester_end", "Semester End"),
                            ("event", "Event"),
                            ("deadline", "Deadline"),
                            ("other", "Other"),
                        ],
                        default="event",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "title"],
            },
        ),
    ]
