# Generated by Django 6.0.1 on 2026-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_academic_year_student_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
