# Generated by Django 6.0.1 on 2026-02-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0007_timetable_theme_palette"),
        ("student", "0003_student_address_student_blood_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["student_id"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's division for timetable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.division",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.IntegerField(default=3, help_text="Current semester (1-8)"),
        ),
        migrations.AlterModelTable(
            name="student",
            table="student_student",
        ),
    ]
