# Generated by Django 6.0.1 on 2026-02-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_course_options_alter_grade_options_and_more"),
        ("generator", "0008_alter_division_options_alter_room_options_and_more"),
        ("institution", "0004_alter_institution_options_alter_news_options_and_more"),
        ("student", "0004_alter_student_options_student_division_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolled_students",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's division for timetable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="generator.division",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["institution", "course"], name="student_stu_institu_e84856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["institution", "status"], name="student_stu_institu_af54a9_idx"
            ),
        ),
    ]
