# Generated by Django 6.0.1 on 2026-02-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_course_options_alter_grade_options_and_more"),
        ("generator", "0009_alter_division_options_alter_room_options_and_more"),
        ("institution", "0005_alter_institution_options_alter_news_options_and_more"),
        ("student", "0005_alter_student_course_alter_student_division_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="student_stu_institu_e84856_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_stu_institu_af54a9_idx",
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's division for timetable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.division",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
