# Generated by Django 6.0.1 on 2026-02-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_branch"),
        ("student", "0006_remove_student_student_stu_institu_e84856_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.branch",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
