# Generated by Django 6.0 on 2026-02-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_course_teacher_course_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
