# Generated by Django 6.0.1 on 2026-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_course_duration_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="tuition_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
