# Generated by Django 6.0.1 on 2026-02-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_course_department_course_tuition_fee"),
        ("institution", "0004_alter_institution_options_alter_news_options_and_more"),
        ("student", "0004_alter_student_options_student_division_and_more"),
        ("teacher", "0004_alter_teacher_options_alter_teacher_department_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["code"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["-date_assigned"],
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="taught_courses", to="teacher.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="student.student",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["institution", "department"],
                name="academics_c_institu_658e1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "course"], name="academics_g_student_c042cd_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="course",
            table="academics_course",
        ),
        migrations.AlterModelTable(
            name="grade",
            table="academics_grade",
        ),
    ]
