# Generated by Django 6.0.1 on 2026-02-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_course_options_alter_grade_options_and_more"),
        ("institution", "0005_alter_institution_options_alter_news_options_and_more"),
        ("student", "0005_alter_student_course_alter_student_division_and_more"),
        ("teacher", "0005_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="academics_c_institu_658e1a_idx",
        ),
        migrations.RemoveIndex(
            model_name="grade",
            name="academics_g_student_c042cd_idx",
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(blank=True, to="teacher.teacher"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.course"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AlterModelTable(
            name="course",
            table=None,
        ),
        migrations.AlterModelTable(
            name="grade",
            table=None,
        ),
    ]
