# Generated by Django 6.0.1 on 2026-02-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_course_options_alter_grade_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
    ]
