# Generated by Django 6.0.1 on 2026-02-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_branch"),
        ("institution", "0008_academiccalendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTypeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Regular Teaching", "Regular Teaching"),
                            ("Test", "Test"),
                            ("Reading Holiday", "Reading Holiday"),
                            ("Public Holiday", "Public Holiday"),
                            ("Semester Break", "Semester Break"),
                            ("Festival Holiday", "Festival Holiday"),
                            (
                                "Project / Practical Evaluation",
                                "Project / Practical Evaluation",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("color_code", models.CharField(default="#2563EB", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "event_type_colors",
                "ordering": ["event_type"],
            },
        ),
        migrations.CreateModel(
            name="AcademicCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=30)),
                ("year", models.CharField(max_length=20)),
                ("shared_with_students", models.BooleanField(default=False)),
                ("shared_with_teachers", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendars",
                        to="institution.department",
                    ),
                ),
            ],
            options={
                "db_table": "academic_calendar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Regular Teaching", "Regular Teaching"),
                            ("Test", "Test"),
                            ("Reading Holiday", "Reading Holiday"),
                            ("Public Holiday", "Public Holiday"),
                            ("Semester Break", "Semester Break"),
                            ("Festival Holiday", "Festival Holiday"),
                            (
                                "Project / Practical Evaluation",
                                "Project / Practical Evaluation",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("color_code", models.CharField(default="#2563EB", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="academics.academiccalendar",
                    ),
                ),
            ],
            options={
                "db_table": "calendar_events",
                "ordering": ["date", "id"],
            },
        ),
    ]
