# Generated by Django 6.0.1 on 2026-02-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_eventtypecolor_academiccalendar_calendarevent"),
        ("institution", "0008_academiccalendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendar",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_calendars_new",
                to="institution.institution",
            ),
        ),
    ]
