# Generated by Django 6.0.1 on 2026-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_timetable_alter_timetableentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="days_count",
            field=models.IntegerField(default=6),
        ),
    ]
