# Generated by Django 6.0.1 on 2026-02-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_course_department_course_tuition_fee"),
        ("generator", "0003_timetable_days_count"),
        ("institution", "0003_news"),
        ("teacher", "0003_teacher_address_teacher_contract_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.DeleteModel(
            name="Faculty",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
