# Generated by Django 6.0.1 on 2026-02-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0004_alter_timetableentry_faculty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="heading_1",
            field=models.CharField(
                default="L.J. INSTITUTE OF ENGINEERING AND TECHNOLOGY, L.J. UNIVERSITY",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="heading_2",
            field=models.CharField(default="SY CE/IT- 4 DEPARTMENT", max_length=255),
        ),
    ]
