# Generated by Django 6.0.1 on 2026-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0005_timetable_heading_1_timetable_heading_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="footer_hod",
            field=models.TextField(
                default="Prof. Sneha Shah\nHOD- SY4 (CST/CSIT/CSE_CS/MA&CP)"
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="footer_prepared_by",
            field=models.TextField(
                default="Prepared By:\nProf. Darshan Bhatt (DVB)\nProf. Priyanka Sinha (PCS)"
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="footer_semester_text",
            field=models.CharField(default="SEMESTER III", max_length=100),
        ),
    ]
