# Generated by Django 6.0.1 on 2026-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "generator",
            "0006_timetable_footer_hod_timetable_footer_prepared_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="theme_palette",
            field=models.CharField(default="classic", max_length=20),
        ),
    ]
