# Generated by Django 6.0.1 on 2026-02-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_course_options_alter_grade_options_and_more"),
        ("generator", "0007_timetable_theme_palette"),
        ("institution", "0004_alter_institution_options_alter_news_options_and_more"),
        ("teacher", "0004_alter_teacher_options_alter_teacher_department_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={
                "ordering": ["name"],
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["number"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["lecture_number"],
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
            },
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Timetable",
                "verbose_name_plural": "Timetables",
            },
        ),
        migrations.AlterModelOptions(
            name="timetableentry",
            options={
                "ordering": ["day", "timeslot"],
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
            },
        ),
        migrations.AlterField(
            model_name="division",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(db_index=True, help_text="e.g., D1", max_length=10),
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(
                db_index=True, help_text="e.g., 410-C", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="generator.division",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="teacher.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="generator.room",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="timeslot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="generator.timeslot",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["timetable", "day", "division"],
                name="generator_t_timetab_48ac15_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="division",
            table="generator_division",
        ),
        migrations.AlterModelTable(
            name="room",
            table="generator_room",
        ),
        migrations.AlterModelTable(
            name="timeslot",
            table="generator_timeslot",
        ),
        migrations.AlterModelTable(
            name="timetable",
            table="generator_timetable",
        ),
        migrations.AlterModelTable(
            name="timetableentry",
            table="generator_timetableentry",
        ),
    ]
