# Generated by Django 6.0.1 on 2026-02-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_course_options_alter_grade_options_and_more"),
        ("generator", "0008_alter_division_options_alter_room_options_and_more"),
        ("institution", "0005_alter_institution_options_alter_news_options_and_more"),
        ("teacher", "0005_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"ordering": ["lecture_number"]},
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={},
        ),
        migrations.AlterModelOptions(
            name="timetableentry",
            options={"verbose_name_plural": "Timetable Entries"},
        ),
        migrations.RemoveIndex(
            model_name="timetableentry",
            name="generator_t_timetab_48ac15_idx",
        ),
        migrations.AlterField(
            model_name="division",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(help_text="e.g., D1", max_length=10),
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(help_text="e.g., 410-C", max_length=20),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="generator.division"
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="generator.room",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="timeslot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="generator.timeslot"
            ),
        ),
        migrations.AlterModelTable(
            name="division",
            table=None,
        ),
        migrations.AlterModelTable(
            name="room",
            table=None,
        ),
        migrations.AlterModelTable(
            name="timeslot",
            table=None,
        ),
        migrations.AlterModelTable(
            name="timetable",
            table=None,
        ),
        migrations.AlterModelTable(
            name="timetableentry",
            table=None,
        ),
    ]
