# Generated by Django 6.0.1 on 2026-02-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_course_department"),
        ("generator", "0009_alter_division_options_alter_room_options_and_more"),
        ("teacher", "0007_teacher_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teacher.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.room",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="timetable",
            field=models.ForeignKey(
                default=17,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="generator.timetable",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={
                ("division", "timeslot", "day"),
                ("faculty", "timeslot", "day"),
                ("room", "timeslot", "day"),
            },
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["division"], name="generator_t_divisio_a256cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["timeslot"], name="generator_t_timeslo_013dd2_idx"
            ),
        ),
    ]
