# Generated by Django 6.0.1 on 2026-02-17 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_course_department"),
        ("generator", "0010_alter_timetableentry_faculty_and_more"),
        ("institution", "0006_alter_department_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="institution.department",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["department"], name="generator_t_departm_2312b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["course"], name="generator_t_course__b00664_idx"
            ),
        ),
    ]
