# Generated by Django 6.0.1 on 2026-02-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_course_department"),
        ("generator", "0011_timetable_course_timetable_created_by_and_more"),
        ("institution", "0006_alter_department_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="timetable",
            name="generator_t_departm_2312b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetable",
            name="generator_t_course__b00664_idx",
        ),
        migrations.AddField(
            model_name="timetable",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.department",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="status",
            field=models.CharField(
                blank=True, default="Draft", max_length=20, null=True
            ),
        ),
    ]
