# Generated by Django 6.0.1 on 2026-02-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_branch"),
        ("generator", "0012_remove_timetable_generator_t_departm_2312b6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.branch",
            ),
        ),
    ]
